
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: May 19 2025 19:13:22 IST (May 19 2025 13:43:22 UTC)

// Verification Directory fv/project 

module half_adder(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  AOI2BB1X1 g26__8780(.A0N (b), .A1N (a), .B0 (carry), .Y (sum));
  CLKAND2X2 g27__4296(.A (b), .B (a), .Y (carry));
endmodule

module half_adder_65(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  wire n_1;
  AOI21X1 g27__3772(.A0 (b), .A1 (a), .B0 (n_1), .Y (sum));
  NOR2XL g28__1474(.A (b), .B (a), .Y (n_1));
  CLKAND2X3 g2__4547(.A (b), .B (a), .Y (carry));
endmodule

module vedic_2x2(a, b, p);
  input [1:0] a, b;
  output [3:0] p;
  wire [1:0] a, b;
  wire [3:0] p;
  wire c1, n_0, n_1, w1, w2, w3;
  half_adder ha1(.a (w1), .b (w2), .sum (p[1]), .carry (c1));
  half_adder_65 ha2(.a (c1), .b (w3), .sum (p[2]), .carry (p[3]));
  AND2XL g41__9682(.A (b[0]), .B (a[0]), .Y (p[0]));
  AND2X1 g42__2683(.A (b[1]), .B (a[1]), .Y (w3));
  CLKINVX1 g43(.A (n_1), .Y (w2));
  CLKINVX1 g44(.A (n_0), .Y (w1));
  NAND2X2 g45__1309(.A (b[1]), .B (a[0]), .Y (n_1));
  NAND2X1 g46__6877(.A (b[0]), .B (a[1]), .Y (n_0));
endmodule

module half_adder_64(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  wire n_1;
  NOR2X2 g26__2900(.A (n_1), .B (carry), .Y (sum));
  NOR2X1 g27__2391(.A (b), .B (a), .Y (n_1));
  CLKAND2X6 g28__7675(.A (b), .B (a), .Y (carry));
endmodule

module half_adder_63(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  wire n_1;
  AOI21X4 g28__7118(.A0 (b), .A1 (a), .B0 (n_1), .Y (sum));
  NOR2X4 g29__8757(.A (b), .B (a), .Y (n_1));
  CLKAND2X3 g30__1786(.A (b), .B (a), .Y (carry));
endmodule

module vedic_2x2_80(a, b, p);
  input [1:0] a, b;
  output [3:0] p;
  wire [1:0] a, b;
  wire [3:0] p;
  wire c1, n_0, n_1, w1, w2, w3;
  half_adder_64 ha1(.a (w1), .b (w2), .sum (p[1]), .carry (c1));
  half_adder_63 ha2(.a (c1), .b (w3), .sum (p[2]), .carry (p[3]));
  CLKINVX3 g45(.A (n_1), .Y (w2));
  CLKINVX2 g46(.A (n_0), .Y (w1));
  NAND2X6 g47__5953(.A (b[1]), .B (a[0]), .Y (n_1));
  NAND2X4 g48__5703(.A (b[0]), .B (a[1]), .Y (n_0));
  CLKAND2X2 g2__7114(.A (b[0]), .B (a[0]), .Y (p[0]));
  CLKAND2X4 g49__5266(.A (b[1]), .B (a[1]), .Y (w3));
endmodule

module half_adder_62(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  wire n_2;
  AOI21X2 g26__2250(.A0 (a), .A1 (b), .B0 (n_2), .Y (sum));
  NOR2X1 g27__6083(.A (b), .B (a), .Y (n_2));
  CLKAND2X6 g28__2703(.A (b), .B (a), .Y (carry));
endmodule

module half_adder_61(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  wire n_1;
  AOI21X2 g28__5795(.A0 (b), .A1 (a), .B0 (n_1), .Y (sum));
  NOR2X2 g29__7344(.A (b), .B (a), .Y (n_1));
  CLKAND2X6 g30__1840(.A (b), .B (a), .Y (carry));
endmodule

module vedic_2x2_79(a, b, p);
  input [1:0] a, b;
  output [3:0] p;
  wire [1:0] a, b;
  wire [3:0] p;
  wire c1, n_0, n_1, w1, w2, w3;
  half_adder_62 ha1(.a (w1), .b (w2), .sum (p[1]), .carry (c1));
  half_adder_61 ha2(.a (c1), .b (w3), .sum (p[2]), .carry (p[3]));
  CLKINVX2 g45(.A (n_1), .Y (w2));
  CLKINVX2 g46(.A (n_0), .Y (w1));
  NAND2X4 g47__5019(.A (b[1]), .B (a[0]), .Y (n_1));
  NAND2X4 g48__1857(.A (b[0]), .B (a[1]), .Y (n_0));
  AND2X1 g2__9906(.A (b[0]), .B (a[0]), .Y (p[0]));
  CLKAND2X2 g49__8780(.A (b[1]), .B (a[1]), .Y (w3));
endmodule

module half_adder_60(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  wire n_1;
  NOR2X2 g26__4296(.A (n_1), .B (carry), .Y (sum));
  NOR2X1 g27__3772(.A (b), .B (a), .Y (n_1));
  AND2X6 g28__1474(.A (a), .B (b), .Y (carry));
endmodule

module half_adder_59(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  wire n_1;
  AOI21X1 g26__4547(.A0 (b), .A1 (a), .B0 (n_1), .Y (sum));
  NOR2XL g27__9682(.A (b), .B (a), .Y (n_1));
  AND2X1 g28__2683(.A (b), .B (a), .Y (carry));
endmodule

module vedic_2x2_78(a, b, p);
  input [1:0] a, b;
  output [3:0] p;
  wire [1:0] a, b;
  wire [3:0] p;
  wire c1, w1, w2, w3;
  half_adder_60 ha1(.a (w1), .b (w2), .sum (p[1]), .carry (c1));
  half_adder_59 ha2(.a (c1), .b (w3), .sum (p[2]), .carry (p[3]));
  AND2X1 g42__1309(.A (b[1]), .B (a[1]), .Y (w3));
  CLKAND2X2 g2__6877(.A (b[1]), .B (a[0]), .Y (w2));
  CLKAND2X3 g49__2900(.A (b[0]), .B (a[1]), .Y (w1));
  AND2X1 g50__2391(.A (b[0]), .B (a[0]), .Y (p[0]));
endmodule

module half_adder_58(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  AOI2BB1X1 g26__7675(.A0N (b), .A1N (a), .B0 (carry), .Y (sum));
  CLKAND2X2 g27__7118(.A (b), .B (a), .Y (carry));
endmodule

module half_adder_57(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  CLKAND2X2 g28__5953(.A (b), .B (a), .Y (carry));
  CLKXOR2X1 g2(.A (b), .B (a), .Y (sum));
endmodule

module vedic_2x2_77(a, b, p);
  input [1:0] a, b;
  output [3:0] p;
  wire [1:0] a, b;
  wire [3:0] p;
  wire c1, n_0, n_1, w1, w2, w3;
  half_adder_58 ha1(.a (w1), .b (w2), .sum (p[1]), .carry (c1));
  half_adder_57 ha2(.a (c1), .b (w3), .sum (p[2]), .carry (p[3]));
  AND2X1 g41__5703(.A (b[0]), .B (a[0]), .Y (p[0]));
  AND2X1 g42__7114(.A (b[1]), .B (a[1]), .Y (w3));
  CLKINVX1 g43(.A (n_1), .Y (w2));
  CLKINVX1 g44(.A (n_0), .Y (w1));
  NAND2X1 g45__5266(.A (b[1]), .B (a[0]), .Y (n_1));
  NAND2X1 g46__2250(.A (b[0]), .B (a[1]), .Y (n_0));
endmodule

module half_adder_56(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  wire n_1;
  NOR2X2 g26__6083(.A (n_1), .B (carry), .Y (sum));
  NOR2XL g27__2703(.A (b), .B (a), .Y (n_1));
  CLKAND2X3 g28__5795(.A (b), .B (a), .Y (carry));
endmodule

module half_adder_55(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  wire n_1;
  AOI21X2 g26__7344(.A0 (b), .A1 (a), .B0 (n_1), .Y (sum));
  NOR2X1 g27__1840(.A (b), .B (a), .Y (n_1));
  CLKAND2X2 g28__5019(.A (b), .B (a), .Y (carry));
endmodule

module vedic_2x2_76(a, b, p);
  input [1:0] a, b;
  output [3:0] p;
  wire [1:0] a, b;
  wire [3:0] p;
  wire c1, n_1, n_2, n_3, n_8, w1, w2, w3;
  half_adder_56 ha1(.a (w1), .b (w2), .sum (p[1]), .carry (c1));
  half_adder_55 ha2(.a (c1), .b (w3), .sum (p[2]), .carry (p[3]));
  NOR2X1 g41__1857(.A (n_1), .B (n_8), .Y (p[0]));
  AND2X1 g42__9906(.A (b[1]), .B (a[1]), .Y (w3));
  NOR2X2 g43__8780(.A (n_3), .B (n_8), .Y (w2));
  NOR2X2 g44__4296(.A (n_1), .B (n_2), .Y (w1));
  CLKINVX3 g45(.A (b[1]), .Y (n_3));
  CLKINVX2 g46(.A (a[1]), .Y (n_2));
  CLKINVX3 g47(.A (b[0]), .Y (n_1));
  INVX3 fopt49(.A (a[0]), .Y (n_8));
endmodule

module half_adder_54(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  wire n_1;
  NOR2X2 g26__3772(.A (n_1), .B (carry), .Y (sum));
  NOR2XL g27__1474(.A (b), .B (a), .Y (n_1));
  CLKAND2X6 g28__4547(.A (a), .B (b), .Y (carry));
endmodule

module half_adder_53(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  wire n_1;
  AOI21X4 g28__9682(.A0 (b), .A1 (a), .B0 (n_1), .Y (sum));
  NOR2X4 g29__2683(.A (b), .B (a), .Y (n_1));
  CLKAND2X3 g30__1309(.A (b), .B (a), .Y (carry));
endmodule

module vedic_2x2_75(a, b, p);
  input [1:0] a, b;
  output [3:0] p;
  wire [1:0] a, b;
  wire [3:0] p;
  wire c1, n_0, n_1, w1, w2, w3;
  half_adder_54 ha1(.a (w1), .b (w2), .sum (p[1]), .carry (c1));
  half_adder_53 ha2(.a (c1), .b (w3), .sum (p[2]), .carry (p[3]));
  CLKINVX2 g44(.A (n_1), .Y (w2));
  CLKINVX2 g45(.A (n_0), .Y (w1));
  NAND2X4 g46__6877(.A (b[1]), .B (a[0]), .Y (n_1));
  NAND2X4 g47__2900(.A (b[0]), .B (a[1]), .Y (n_0));
  CLKAND2X4 g2__2391(.A (b[1]), .B (a[1]), .Y (w3));
  AND2X1 g50__7675(.A (b[0]), .B (a[0]), .Y (p[0]));
endmodule

module half_adder_52(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  wire n_1;
  NOR2X2 g26__7118(.A (n_1), .B (carry), .Y (sum));
  NOR2X1 g27__8757(.A (b), .B (a), .Y (n_1));
  CLKAND2X3 g28__1786(.A (b), .B (a), .Y (carry));
endmodule

module half_adder_51(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  ADDHXL g26__5953(.A (b), .B (a), .CO (carry), .S (sum));
endmodule

module vedic_2x2_74(a, b, p);
  input [1:0] a, b;
  output [3:0] p;
  wire [1:0] a, b;
  wire [3:0] p;
  wire c1, n_1, n_7, n_8, w1, w3;
  half_adder_52 ha1(.a (w1), .b (n_8), .sum (p[1]), .carry (c1));
  half_adder_51 ha2(.a (c1), .b (w3), .sum (p[2]), .carry (p[3]));
  NOR2XL g41__5703(.A (n_7), .B (n_1), .Y (p[0]));
  AND2X1 g42__7114(.A (b[1]), .B (a[1]), .Y (w3));
  CLKINVX1 g47(.A (b[0]), .Y (n_1));
  NOR2BX1 g2__2250(.AN (a[1]), .B (n_1), .Y (w1));
  CLKINVX2 fopt(.A (a[0]), .Y (n_7));
  NOR2BX1 g2(.AN (b[1]), .B (n_7), .Y (n_8));
endmodule

module half_adder_50(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  AOI2BB1X1 g26__6083(.A0N (b), .A1N (a), .B0 (carry), .Y (sum));
  CLKAND2X3 g27__2703(.A (b), .B (a), .Y (carry));
endmodule

module half_adder_49(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  CLKAND2X3 g2__1840(.A (b), .B (a), .Y (carry));
  CLKXOR2X1 g2(.A (b), .B (a), .Y (sum));
endmodule

module vedic_2x2_73(a, b, p);
  input [1:0] a, b;
  output [3:0] p;
  wire [1:0] a, b;
  wire [3:0] p;
  wire c1, n_0, n_1, w1, w2, w3;
  half_adder_50 ha1(.a (w1), .b (w2), .sum (p[1]), .carry (c1));
  half_adder_49 ha2(.a (c1), .b (w3), .sum (p[2]), .carry (p[3]));
  AND2X1 g41__5019(.A (b[0]), .B (a[0]), .Y (p[0]));
  AND2X1 g42__1857(.A (b[1]), .B (a[1]), .Y (w3));
  CLKINVX1 g43(.A (n_1), .Y (w2));
  CLKINVX1 g44(.A (n_0), .Y (w1));
  NAND2X2 g45__9906(.A (b[1]), .B (a[0]), .Y (n_1));
  NAND2X1 g46__8780(.A (b[0]), .B (a[1]), .Y (n_0));
endmodule

module half_adder_48(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  wire n_1;
  AOI21X1 g26__4296(.A0 (a), .A1 (b), .B0 (n_1), .Y (sum));
  NOR2X1 g27__3772(.A (b), .B (a), .Y (n_1));
  CLKAND2X3 g28__1474(.A (b), .B (a), .Y (carry));
endmodule

module half_adder_47(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  wire n_1;
  AOI21X2 g28__4547(.A0 (b), .A1 (a), .B0 (n_1), .Y (sum));
  NOR2X2 g29__9682(.A (b), .B (a), .Y (n_1));
  CLKAND2X3 g30__2683(.A (b), .B (a), .Y (carry));
endmodule

module vedic_2x2_72(a, b, p);
  input [1:0] a, b;
  output [3:0] p;
  wire [1:0] a, b;
  wire [3:0] p;
  wire c1, n_0, n_1, w1, w2, w3;
  half_adder_48 ha1(.a (w1), .b (w2), .sum (p[1]), .carry (c1));
  half_adder_47 ha2(.a (c1), .b (w3), .sum (p[2]), .carry (p[3]));
  CLKINVX2 g44(.A (n_1), .Y (w2));
  CLKINVX2 g45(.A (n_0), .Y (w1));
  NAND2X4 g46__1309(.A (b[1]), .B (a[0]), .Y (n_1));
  NAND2X4 g47__6877(.A (b[0]), .B (a[1]), .Y (n_0));
  CLKAND2X4 g2__2900(.A (b[1]), .B (a[1]), .Y (w3));
  AND2X1 g50__2391(.A (b[0]), .B (a[0]), .Y (p[0]));
endmodule

module half_adder_46(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  wire n_1;
  NOR2X2 g26__7675(.A (n_1), .B (carry), .Y (sum));
  NOR2XL g27__7118(.A (b), .B (a), .Y (n_1));
  CLKAND2X6 g28__8757(.A (b), .B (a), .Y (carry));
endmodule

module half_adder_45(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  wire n_1;
  AOI21X4 g28__1786(.A0 (b), .A1 (a), .B0 (n_1), .Y (sum));
  NOR2X4 g29__5953(.A (b), .B (a), .Y (n_1));
  CLKAND2X3 g30__5703(.A (b), .B (a), .Y (carry));
endmodule

module vedic_2x2_71(a, b, p);
  input [1:0] a, b;
  output [3:0] p;
  wire [1:0] a, b;
  wire [3:0] p;
  wire c1, n_0, n_1, w1, w2, w3;
  half_adder_46 ha1(.a (w1), .b (w2), .sum (p[1]), .carry (c1));
  half_adder_45 ha2(.a (c1), .b (w3), .sum (p[2]), .carry (p[3]));
  CLKINVX4 g44(.A (n_1), .Y (w2));
  CLKINVX3 g45(.A (n_0), .Y (w1));
  NAND2X8 g46__7114(.A (b[1]), .B (a[0]), .Y (n_1));
  NAND2X4 g47__5266(.A (b[0]), .B (a[1]), .Y (n_0));
  CLKAND2X4 g2__2250(.A (b[1]), .B (a[1]), .Y (w3));
  AND2X1 g50__6083(.A (b[0]), .B (a[0]), .Y (p[0]));
endmodule

module half_adder_44(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  wire n_1;
  NOR2X4 g28__2703(.A (n_1), .B (carry), .Y (sum));
  NOR2X1 g29__5795(.A (b), .B (a), .Y (n_1));
  CLKAND2X2 g2__7344(.A (a), .B (b), .Y (carry));
endmodule

module half_adder_43(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  ADDHX1 g26__1840(.A (b), .B (a), .CO (carry), .S (sum));
endmodule

module vedic_2x2_70(a, b, p);
  input [1:0] a, b;
  output [3:0] p;
  wire [1:0] a, b;
  wire [3:0] p;
  wire c1, n_0, n_1, w1, w2, w3;
  half_adder_44 ha1(.a (w1), .b (w2), .sum (p[1]), .carry (c1));
  half_adder_43 ha2(.a (c1), .b (w3), .sum (p[2]), .carry (p[3]));
  AND2X1 g43__5019(.A (b[1]), .B (a[1]), .Y (w3));
  CLKINVX1 g44(.A (n_1), .Y (w2));
  CLKINVX1 g45(.A (n_0), .Y (w1));
  NAND2X2 g46__1857(.A (b[1]), .B (a[0]), .Y (n_1));
  NAND2X4 g47__9906(.A (b[0]), .B (a[1]), .Y (n_0));
  CLKAND2X2 g2__8780(.A (b[0]), .B (a[0]), .Y (p[0]));
endmodule

module half_adder_42(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  AOI2BB1X1 g26__4296(.A0N (b), .A1N (a), .B0 (carry), .Y (sum));
  CLKAND2X2 g27__3772(.A (b), .B (a), .Y (carry));
endmodule

module half_adder_41(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  wire n_1;
  AOI21X1 g26__1474(.A0 (b), .A1 (a), .B0 (n_1), .Y (sum));
  NOR2XL g27__4547(.A (b), .B (a), .Y (n_1));
  AND2X1 g28__9682(.A (b), .B (a), .Y (carry));
endmodule

module vedic_2x2_69(a, b, p);
  input [1:0] a, b;
  output [3:0] p;
  wire [1:0] a, b;
  wire [3:0] p;
  wire c1, w1, w2, w3;
  half_adder_42 ha1(.a (w1), .b (w2), .sum (p[1]), .carry (c1));
  half_adder_41 ha2(.a (c1), .b (w3), .sum (p[2]), .carry (p[3]));
  AND2X1 g41__2683(.A (b[0]), .B (a[0]), .Y (p[0]));
  AND2X1 g42__1309(.A (b[1]), .B (a[1]), .Y (w3));
  CLKAND2X2 g2__6877(.A (b[1]), .B (a[0]), .Y (w2));
  CLKAND2X2 g47__2900(.A (b[0]), .B (a[1]), .Y (w1));
endmodule

module half_adder_40(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  AOI2BB1X1 g26__2391(.A0N (b), .A1N (a), .B0 (carry), .Y (sum));
  AND2X1 g27__7675(.A (b), .B (a), .Y (carry));
endmodule

module half_adder_39(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  wire n_1;
  AOI21X1 g26__7118(.A0 (b), .A1 (a), .B0 (n_1), .Y (sum));
  NOR2XL g27__8757(.A (b), .B (a), .Y (n_1));
  AND2X1 g28__1786(.A (b), .B (a), .Y (carry));
endmodule

module vedic_2x2_68(a, b, p);
  input [1:0] a, b;
  output [3:0] p;
  wire [1:0] a, b;
  wire [3:0] p;
  wire c1, w1, w2, w3;
  half_adder_40 ha1(.a (w1), .b (w2), .sum (p[1]), .carry (c1));
  half_adder_39 ha2(.a (c1), .b (w3), .sum (p[2]), .carry (p[3]));
  AND2X1 g41__5953(.A (b[0]), .B (a[0]), .Y (p[0]));
  AND2X1 g42__5703(.A (b[1]), .B (a[1]), .Y (w3));
  AND2X1 g2__7114(.A (b[1]), .B (a[0]), .Y (w2));
  AND2X1 g49__5266(.A (b[0]), .B (a[1]), .Y (w1));
endmodule

module half_adder_38(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  ADDHX1 g26__2250(.A (a), .B (b), .CO (carry), .S (sum));
endmodule

module half_adder_37(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  wire n_1;
  AOI21X1 g26__6083(.A0 (b), .A1 (a), .B0 (n_1), .Y (sum));
  NOR2XL g27__2703(.A (b), .B (a), .Y (n_1));
  AND2X1 g28__5795(.A (b), .B (a), .Y (carry));
endmodule

module vedic_2x2_67(a, b, p);
  input [1:0] a, b;
  output [3:0] p;
  wire [1:0] a, b;
  wire [3:0] p;
  wire c1, w1, w2, w3;
  half_adder_38 ha1(.a (w1), .b (w2), .sum (p[1]), .carry (c1));
  half_adder_37 ha2(.a (c1), .b (w3), .sum (p[2]), .carry (p[3]));
  AND2X1 g41__7344(.A (b[0]), .B (a[0]), .Y (p[0]));
  AND2X1 g42__1840(.A (b[1]), .B (a[1]), .Y (w3));
  CLKAND2X2 g2__5019(.A (b[1]), .B (a[0]), .Y (w2));
  CLKAND2X2 g47__1857(.A (b[0]), .B (a[1]), .Y (w1));
endmodule

module half_adder_36(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  ADDHX1 g26__9906(.A (a), .B (b), .CO (carry), .S (sum));
endmodule

module half_adder_35(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  ADDHX1 g26__8780(.A (b), .B (a), .CO (carry), .S (sum));
endmodule

module vedic_2x2_66(a, b, p);
  input [1:0] a, b;
  output [3:0] p;
  wire [1:0] a, b;
  wire [3:0] p;
  wire c1, w1, w2, w3;
  half_adder_36 ha1(.a (w1), .b (w2), .sum (p[1]), .carry (c1));
  half_adder_35 ha2(.a (c1), .b (w3), .sum (p[2]), .carry (p[3]));
  AND2X1 g41__4296(.A (b[0]), .B (a[0]), .Y (p[0]));
  AND2X1 g42__3772(.A (b[1]), .B (a[1]), .Y (w3));
  AND2X1 g43__1474(.A (b[1]), .B (a[0]), .Y (w2));
  AND2X1 g44__4547(.A (b[0]), .B (a[1]), .Y (w1));
endmodule

module vedic_8x8_comb(a, b, p);
  input [7:0] a, b;
  output [15:0] p;
  wire [7:0] a, b;
  wire [15:0] p;
  wire [3:0] u0_m0;
  wire [3:0] u0_m1;
  wire [3:0] u0_m2;
  wire [3:0] u0_m3;
  wire [3:0] u1_m0;
  wire [3:0] u1_m1;
  wire [3:0] u1_m2;
  wire [3:0] u1_m3;
  wire [3:0] u2_m0;
  wire [3:0] u2_m1;
  wire [3:0] u2_m2;
  wire [3:0] u2_m3;
  wire [3:0] u3_m0;
  wire [3:0] u3_m1;
  wire [3:0] u3_m2;
  wire [3:0] u3_m3;
  wire csa_tree_add_69_22_groupi_n_0, csa_tree_add_69_22_groupi_n_1,
       csa_tree_add_69_22_groupi_n_2, csa_tree_add_69_22_groupi_n_3,
       csa_tree_add_69_22_groupi_n_5, csa_tree_add_69_22_groupi_n_6,
       csa_tree_add_69_22_groupi_n_7, csa_tree_add_69_22_groupi_n_8;
  wire csa_tree_add_69_22_groupi_n_9, csa_tree_add_69_22_groupi_n_10,
       csa_tree_add_69_22_groupi_n_11, csa_tree_add_69_22_groupi_n_12,
       csa_tree_add_69_22_groupi_n_13, csa_tree_add_69_22_groupi_n_14,
       csa_tree_add_69_22_groupi_n_16, csa_tree_add_69_22_groupi_n_19;
  wire csa_tree_add_69_22_groupi_n_20, csa_tree_add_69_22_groupi_n_21,
       csa_tree_add_69_22_groupi_n_22, csa_tree_add_69_22_groupi_n_23,
       csa_tree_add_69_22_groupi_n_24, csa_tree_add_69_22_groupi_n_25,
       csa_tree_add_69_22_groupi_n_26, csa_tree_add_69_22_groupi_n_27;
  wire csa_tree_add_69_22_groupi_n_29, csa_tree_add_69_22_groupi_n_30,
       csa_tree_add_69_22_groupi_n_31, csa_tree_add_69_22_groupi_n_32,
       csa_tree_add_69_22_groupi_n_33, csa_tree_add_69_22_groupi_n_34,
       csa_tree_add_69_22_groupi_n_36, csa_tree_add_69_22_groupi_n_37;
  wire csa_tree_add_69_22_groupi_n_38, csa_tree_add_69_22_groupi_n_39,
       csa_tree_add_69_22_groupi_n_40, csa_tree_add_69_22_groupi_n_41,
       csa_tree_add_69_22_groupi_n_42, csa_tree_add_69_22_groupi_n_43,
       csa_tree_add_69_22_groupi_n_44, csa_tree_add_69_22_groupi_n_46;
  wire csa_tree_add_69_22_groupi_n_47, csa_tree_add_69_22_groupi_n_48,
       csa_tree_add_69_22_groupi_n_49, csa_tree_add_69_22_groupi_n_50,
       csa_tree_add_69_22_groupi_n_51, csa_tree_add_69_22_groupi_n_52,
       csa_tree_add_69_22_groupi_n_53, csa_tree_add_69_22_groupi_n_54;
  wire csa_tree_add_69_22_groupi_n_55, csa_tree_add_69_22_groupi_n_56,
       csa_tree_add_69_22_groupi_n_57, csa_tree_add_69_22_groupi_n_58,
       csa_tree_add_69_22_groupi_n_59, csa_tree_add_69_22_groupi_n_60,
       csa_tree_add_69_22_groupi_n_61, csa_tree_add_69_22_groupi_n_62;
  wire csa_tree_add_69_22_groupi_n_64, csa_tree_add_69_22_groupi_n_65,
       csa_tree_add_69_22_groupi_n_66, csa_tree_add_69_22_groupi_n_67,
       csa_tree_add_69_22_groupi_n_68, csa_tree_add_69_22_groupi_n_69,
       csa_tree_add_69_22_groupi_n_70, csa_tree_add_69_22_groupi_n_72;
  wire csa_tree_add_69_22_groupi_n_73, csa_tree_add_69_22_groupi_n_74,
       csa_tree_add_69_22_groupi_n_75, csa_tree_add_69_22_groupi_n_76,
       csa_tree_add_69_22_groupi_n_77, csa_tree_add_69_22_groupi_n_79,
       csa_tree_add_69_22_groupi_n_80, csa_tree_add_69_22_groupi_n_81;
  wire csa_tree_add_69_22_groupi_n_82, csa_tree_add_69_22_groupi_n_83,
       csa_tree_add_69_22_groupi_n_84, csa_tree_add_69_22_groupi_n_85,
       csa_tree_add_69_22_groupi_n_86, csa_tree_add_69_22_groupi_n_90,
       csa_tree_add_69_22_groupi_n_92, csa_tree_add_69_22_groupi_n_94;
  wire csa_tree_add_69_22_groupi_n_95, csa_tree_add_69_22_groupi_n_96,
       csa_tree_add_69_22_groupi_n_97, csa_tree_add_69_22_groupi_n_98,
       csa_tree_add_69_22_groupi_n_99, csa_tree_add_69_22_groupi_n_100,
       csa_tree_add_69_22_groupi_n_104, csa_tree_add_69_22_groupi_n_105;
  wire csa_tree_add_69_22_groupi_n_106,
       csa_tree_add_69_22_groupi_n_107,
       csa_tree_add_69_22_groupi_n_108,
       csa_tree_add_69_22_groupi_n_109, n_0, n_1, n_2, n_4;
  wire n_5, n_6, n_7, n_8, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_66, n_67, n_68, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_79, n_80, n_81, n_82;
  wire n_83, n_84, n_86, n_87, n_88, n_89, n_90, n_92;
  wire n_93, n_94, n_96, n_97, n_98, n_99, n_100, n_101;
  wire n_102, n_103, n_104, n_105, n_106, n_107, n_108, n_109;
  wire n_110, n_111, n_112, n_113, n_114, n_115, n_116, n_117;
  wire n_118, n_119, n_120, n_121, n_123, n_124, n_125, n_126;
  wire n_127, n_128, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_142, n_143, n_147;
  wire n_148, n_149, n_151, n_152, n_153, n_154, n_155, n_157;
  wire n_158, n_160, n_162, n_163, n_164, n_165, n_167, n_168;
  wire n_169, n_170, n_172, n_173, n_174, n_176, n_177, n_178;
  wire n_180, n_182, n_183, n_184, n_185, n_186, n_187, n_188;
  wire n_189, n_190, n_191, n_192, n_193, n_194, n_196, n_198;
  wire n_199, n_200, n_201, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_211, n_212, n_214, n_215, n_216, n_217, n_218;
  wire n_219, n_220, n_223, n_224, n_225, n_226, n_255, n_256;
  wire n_259, n_261, n_262, n_268, n_275, n_276, n_279, n_280;
  wire n_283, n_286, n_291, n_292, n_293, n_294, n_295, n_296;
  wire n_297, n_298, n_301, n_303, n_304, n_305, n_306, n_307;
  wire n_308, n_309, n_310, n_312, n_313, n_314, n_317, n_319;
  wire n_321, n_323, n_327, n_329, n_331, n_333, n_335, n_337;
  wire n_342, n_346, n_347, n_348;
  vedic_2x2 u0_u0(.a (a[1:0]), .b (b[1:0]), .p ({u0_m0[3:2], p[1:0]}));
  vedic_2x2_80 u0_u1(.a (a[3:2]), .b (b[1:0]), .p (u0_m1));
  vedic_2x2_79 u0_u2(.a (a[1:0]), .b (b[3:2]), .p (u0_m2));
  vedic_2x2_78 u0_u3(.a (a[3:2]), .b (b[3:2]), .p (u0_m3));
  vedic_2x2_77 u1_u0(.a (a[5:4]), .b (b[1:0]), .p (u1_m0));
  vedic_2x2_76 u1_u1(.a (a[7:6]), .b (b[1:0]), .p (u1_m1));
  vedic_2x2_75 u1_u2(.a (a[5:4]), .b (b[3:2]), .p (u1_m2));
  vedic_2x2_74 u1_u3(.a (a[7:6]), .b (b[3:2]), .p (u1_m3));
  vedic_2x2_73 u2_u0(.a (a[1:0]), .b (b[5:4]), .p (u2_m0));
  vedic_2x2_72 u2_u1(.a (a[3:2]), .b (b[5:4]), .p (u2_m1));
  vedic_2x2_71 u2_u2(.a (a[1:0]), .b (b[7:6]), .p (u2_m2));
  vedic_2x2_70 u2_u3(.a (a[3:2]), .b (b[7:6]), .p (u2_m3));
  vedic_2x2_69 u3_u0(.a (a[5:4]), .b (b[5:4]), .p (u3_m0));
  vedic_2x2_68 u3_u1(.a (a[7:6]), .b (b[5:4]), .p (u3_m1));
  vedic_2x2_67 u3_u2(.a (a[5:4]), .b (b[7:6]), .p (u3_m2));
  vedic_2x2_66 u3_u3(.a (a[7:6]), .b (b[7:6]), .p (u3_m3));
  CLKXOR2X1 g3959__9682(.A (u3_m3[3]), .B (n_201), .Y (n_226));
  ADDFX1 g3960__2683(.A (n_188), .B (u3_m3[2]), .CI (n_200), .CO
       (n_201), .S (n_225));
  ADDFX1 g3961__1309(.A (n_189), .B (n_186), .CI (n_199), .CO (n_200),
       .S (n_224));
  OAI21X1 g3962__6877(.A0 (n_301), .A1 (n_192), .B0 (n_193), .Y
       (n_199));
  OAI21X1 g3963__2900(.A0 (n_301), .A1 (n_196), .B0 (n_198), .Y
       (n_223));
  NAND2XL g3964__2391(.A (n_301), .B (n_196), .Y (n_198));
  NOR2BX1 g3967__7118(.AN (n_193), .B (n_192), .Y (n_196));
  AOI22X1 g3969__8757(.A0 (n_295), .A1 (u3_m0[2]), .B0 (u3_m1[0]), .B1
       (u3_m2[0]), .Y (n_194));
  NAND2XL g3970__1786(.A (n_190), .B (n_187), .Y (n_193));
  NOR2X1 g3971__5953(.A (n_187), .B (n_190), .Y (n_192));
  ADDFXL g3973__5703(.A (u3_m3[1]), .B (u3_m1[3]), .CI (u3_m2[3]), .CO
       (n_188), .S (n_189));
  ADDFX1 g3974__7114(.A (u3_m2[1]), .B (u3_m1[1]), .CI (u3_m0[3]), .CO
       (n_190), .S (n_191));
  MXI2XL g3976__5266(.A (n_183), .B (n_184), .S0 (u3_m1[2]), .Y
       (n_187));
  OAI2BB1X1 g3977__2250(.A0N (u3_m3[0]), .A1N (u3_m1[2]), .B0 (n_185),
       .Y (n_186));
  OAI21X1 g3978__6083(.A0 (u3_m3[0]), .A1 (u3_m1[2]), .B0 (u3_m2[2]),
       .Y (n_185));
  INVX1 g3979(.A (n_183), .Y (n_184));
  MXI2X1 g3980__2703(.A (u3_m2[2]), .B (n_182), .S0 (u3_m3[0]), .Y
       (n_183));
  INVX1 g3982(.A (u3_m2[2]), .Y (n_182));
  NAND2X2 g4931__5019(.A (n_180), .B (n_178), .Y (n_214));
  NOR2XL g4932__1857(.A (n_163), .B (n_177), .Y (n_180));
  OAI21X1 g4934__8780(.A0 (n_157), .A1 (n_176), .B0 (n_114), .Y
       (n_212));
  NAND2X1 g4937__3772(.A (n_162), .B (n_174), .Y (n_178));
  AOI21X1 g4938__1474(.A0 (n_172), .A1 (n_154), .B0 (n_164), .Y
       (n_177));
  NAND2XL g4939__4547(.A (n_298), .B (n_173), .Y (n_176));
  NAND2X1 g4941__9682(.A (n_169), .B (n_170), .Y (n_211));
  NAND2X1 g4942__2683(.A (n_348), .B (n_342), .Y (n_174));
  NAND2XL g4944__1309(.A (n_167), .B (n_298), .Y (n_172));
  NAND2X1 g4946__2900(.A (n_309), .B (n_168), .Y (n_173));
  NAND2X1 g4947__2391(.A (n_168), .B (n_158), .Y (n_170));
  NAND3BX1 g4948__7675(.AN (n_116), .B (n_167), .C (n_298), .Y (n_169));
  OAI21XL g4949__7118(.A0 (n_113), .A1 (n_153), .B0 (n_165), .Y (p[3]));
  CLKINVX1 g4950(.A (n_168), .Y (n_167));
  CLKAND2X3 g4952__1786(.A (n_306), .B (n_139), .Y (n_168));
  NAND2XL g4953__5953(.A (n_113), .B (n_153), .Y (n_165));
  NAND2XL g4954__5703(.A (n_155), .B (n_151), .Y (n_164));
  OAI21X1 g4955__7114(.A0 (u0_m3[3]), .A1 (n_149), .B0 (n_160), .Y
       (n_163));
  NOR2XL g4956__5266(.A (u0_m3[3]), .B (n_152), .Y (n_162));
  NAND2XL g4958__6083(.A (u0_m3[3]), .B (n_152), .Y (n_160));
  NAND2BX1 g4960__5795(.AN (n_116), .B (n_298), .Y (n_158));
  NOR2BX1 g4961__7344(.AN (u0_m3[3]), .B (n_148), .Y (n_155));
  NAND2X1 g4962__1840(.A (n_151), .B (n_117), .Y (n_157));
  NOR2XL g4964__1857(.A (n_147), .B (n_116), .Y (n_154));
  CLKINVX1 g4966(.A (n_115), .Y (n_153));
  NOR2XL g4968__9906(.A (u0_m3[2]), .B (n_138), .Y (n_152));
  NAND2X1 g4969__8780(.A (n_136), .B (n_140), .Y (n_151));
  CLKINVX1 g4971(.A (n_148), .Y (n_149));
  CLKINVX1 g4973(.A (n_147), .Y (n_117));
  CLKINVX2 g4976(.A (n_309), .Y (n_116));
  AND2X1 g4977__3772(.A (u0_m3[2]), .B (n_138), .Y (n_148));
  NOR2X2 g4978__1474(.A (n_136), .B (n_140), .Y (n_147));
  BUFX2 g4982(.A (n_135), .Y (n_143));
  NOR2BX1 g4983__9682(.AN (n_115), .B (n_142), .Y (p[2]));
  NOR2BX1 g4985__2683(.AN (n_134), .B (u0_m0[2]), .Y (n_142));
  NAND2BX1 g4986__1309(.AN (n_134), .B (u0_m0[2]), .Y (n_115));
  OAI22X2 g4988__2900(.A0 (n_119), .A1 (n_131), .B0 (u0_m1[3]), .B1
       (n_132), .Y (n_140));
  AOI21X2 g4989__2391(.A0 (u0_m0[3]), .A1 (n_130), .B0 (n_137), .Y
       (n_139));
  NOR2X2 g4990__7675(.A (u0_m0[3]), .B (n_130), .Y (n_137));
  OAI2BB1X1 g4991__7118(.A0N (u0_m2[3]), .A1N (u0_m1[3]), .B0 (n_133),
       .Y (n_138));
  OAI21X1 g4992__8757(.A0 (n_123), .A1 (n_126), .B0 (n_127), .Y
       (n_136));
  OAI21X1 g4993__1786(.A0 (n_124), .A1 (n_128), .B0 (n_125), .Y
       (n_135));
  OAI21X1 g4994__5953(.A0 (u0_m2[3]), .A1 (u0_m1[3]), .B0 (u0_m3[1]),
       .Y (n_133));
  OAI21X1 g4995__5703(.A0 (u0_m1[0]), .A1 (u0_m2[0]), .B0 (n_307), .Y
       (n_134));
  INVX2 g4996(.A (n_131), .Y (n_132));
  OAI22X2 g4997__7114(.A0 (u0_m3[1]), .A1 (n_120), .B0 (u0_m2[3]), .B1
       (n_121), .Y (n_131));
  OAI22X2 g4998__5266(.A0 (u0_m1[1]), .A1 (n_118), .B0 (u0_m2[1]), .B1
       (n_124), .Y (n_130));
  NOR2XL g4999__2250(.A (u0_m2[1]), .B (u0_m0[3]), .Y (n_128));
  NAND2XL g5001__2703(.A (u0_m1[2]), .B (u0_m2[2]), .Y (n_127));
  NOR2XL g5002__5795(.A (u0_m1[2]), .B (u0_m2[2]), .Y (n_126));
  NAND2XL g5003__7344(.A (u0_m2[1]), .B (u0_m0[3]), .Y (n_125));
  CLKINVX1 g5004(.A (u0_m1[1]), .Y (n_124));
  INVX1 g5005(.A (u0_m3[0]), .Y (n_123));
  CLKINVX1 g5007(.A (u0_m3[1]), .Y (n_121));
  CLKINVX1 g5008(.A (u0_m2[3]), .Y (n_120));
  CLKINVX1 g5009(.A (u0_m1[3]), .Y (n_119));
  CLKINVX1 g5010(.A (u0_m2[1]), .Y (n_118));
  OAI2BB1X1 g3987__1840(.A0N (n_298), .A1N (n_173), .B0 (n_157), .Y
       (n_114));
  CLKXOR2X1 g5011__5019(.A (n_139), .B (n_307), .Y (n_113));
  OAI2BB1X2 g5612__1857(.A0N (n_98), .A1N (n_111), .B0 (n_112), .Y
       (n_208));
  AOI31X1 g5613__9906(.A0 (u1_m3[3]), .A1 (n_94), .A2 (n_110), .B0
       (n_104), .Y (n_112));
  MXI2X1 g5614__8780(.A (n_111), .B (n_110), .S0 (n_102), .Y (n_207));
  CLKINVX1 g5616(.A (n_110), .Y (n_111));
  AOI21X2 g5618__4296(.A0 (n_67), .A1 (n_108), .B0 (n_107), .Y (n_110));
  OAI21X1 g5620__3772(.A0 (n_105), .A1 (n_99), .B0 (n_101), .Y (n_109));
  XOR3X1 g5622__1474(.A (n_74), .B (n_88), .C (n_89), .Y (n_204));
  NOR2X1 g5623__4547(.A (n_105), .B (n_92), .Y (n_108));
  OAI21X2 g5624__9682(.A0 (n_101), .A1 (n_92), .B0 (n_96), .Y (n_107));
  NAND2BX1 g5625__2683(.AN (n_100), .B (n_67), .Y (n_106));
  OAI21X1 g5627__1309(.A0 (u1_m3[3]), .A1 (n_94), .B0 (n_103), .Y
       (n_104));
  NAND2X2 g5628__6877(.A (n_97), .B (n_89), .Y (n_105));
  NAND2XL g5629__2900(.A (u1_m3[3]), .B (n_93), .Y (n_103));
  NAND2BX1 g5631__2391(.AN (n_93), .B (n_94), .Y (n_102));
  INVX1 g5632(.A (n_100), .Y (n_101));
  INVX1 g5634(.A (n_67), .Y (n_99));
  NOR2XL g5635__7675(.A (u1_m3[3]), .B (n_93), .Y (n_98));
  NAND2XL g5636__7118(.A (n_74), .B (n_88), .Y (n_97));
  NOR2BX1 g5637__8757(.AN (n_90), .B (n_84), .Y (n_100));
  NAND2BX2 g5638__1786(.AN (n_90), .B (n_84), .Y (n_67));
  INVX1 g5639(.A (n_347), .Y (n_96));
  NAND2XL g5641__5703(.A (u1_m3[2]), .B (n_81), .Y (n_94));
  NOR2XL g5643__7114(.A (u1_m3[2]), .B (n_81), .Y (n_93));
  NOR2X1 g5644__5266(.A (n_268), .B (n_82), .Y (n_92));
  NOR2BX1 g5646__2250(.AN (n_88), .B (n_87), .Y (n_203));
  OAI2BB1X1 g5647__6083(.A0N (u1_m2[1]), .A1N (u1_m1[1]), .B0 (n_83),
       .Y (n_90));
  AOI21X2 g5648__2703(.A0 (u1_m0[3]), .A1 (n_76), .B0 (n_86), .Y
       (n_89));
  NOR2BX1 g5649__5795(.AN (n_80), .B (u1_m0[2]), .Y (n_87));
  NOR2X1 g5650__7344(.A (u1_m0[3]), .B (n_76), .Y (n_86));
  NAND2BX1 g5651__1840(.AN (n_80), .B (u1_m0[2]), .Y (n_88));
  OAI21X1 g5652__5019(.A0 (u1_m1[1]), .A1 (u1_m2[1]), .B0 (u1_m0[3]),
       .Y (n_83));
  XOR3X1 g5654__9906(.A (n_72), .B (u1_m2[2]), .C (u1_m1[2]), .Y
       (n_84));
  OAI21X1 g5655__8780(.A0 (n_72), .A1 (n_73), .B0 (n_75), .Y (n_82));
  OAI2BB1X1 g5656__4296(.A0N (u1_m1[3]), .A1N (u1_m2[3]), .B0 (n_79),
       .Y (n_81));
  OAI21X1 g5657__3772(.A0 (u1_m1[3]), .A1 (u1_m2[3]), .B0 (u1_m3[1]),
       .Y (n_79));
  OAI21X1 g5658__1474(.A0 (u1_m2[0]), .A1 (u1_m1[0]), .B0 (n_74), .Y
       (n_80));
  OAI22X2 g5660__4547(.A0 (u1_m3[1]), .A1 (n_283), .B0 (u1_m2[3]), .B1
       (n_71), .Y (n_77));
  OAI22X2 g5661__9682(.A0 (u1_m2[1]), .A1 (n_286), .B0 (u1_m1[1]), .B1
       (n_68), .Y (n_76));
  NAND2XL g5662__2683(.A (u1_m1[2]), .B (u1_m2[2]), .Y (n_75));
  NOR2XL g5663__1309(.A (u1_m1[2]), .B (u1_m2[2]), .Y (n_73));
  NAND2XL g5664__6877(.A (u1_m1[0]), .B (u1_m2[0]), .Y (n_74));
  CLKINVX1 g5665(.A (u1_m3[0]), .Y (n_72));
  CLKINVX1 g5666(.A (u1_m3[1]), .Y (n_71));
  CLKINVX1 g5670(.A (u1_m2[1]), .Y (n_68));
  INVX1 drc_bufs5672(.A (u1_m1[3]), .Y (n_66));
  XNOR2X1 g5012__2900(.A (n_109), .B (n_62), .Y (n_206));
  CLKXOR2X1 g5678__2391(.A (n_105), .B (n_106), .Y (n_205));
  OR2XL g5679__7675(.A (n_347), .B (n_92), .Y (n_62));
  OAI21X2 g5677__7118(.A0 (n_42), .A1 (n_60), .B0 (n_61), .Y (n_220));
  OAI21X2 g5680__8757(.A0 (n_48), .A1 (n_60), .B0 (n_2), .Y (n_219));
  MXI2X1 g5681__1786(.A (n_58), .B (n_59), .S0 (n_46), .Y (n_218));
  AOI21X1 g5682__5953(.A0 (n_56), .A1 (n_57), .B0 (n_49), .Y (n_61));
  NOR2X2 g5683__5703(.A (n_51), .B (n_55), .Y (n_60));
  INVX1 g5684(.A (n_58), .Y (n_59));
  AOI21X1 g5685__7114(.A0 (n_7), .A1 (n_317), .B0 (n_50), .Y (n_57));
  OAI21X1 g5686__5266(.A0 (n_43), .A1 (n_305), .B0 (n_8), .Y (n_58));
  CLKINVX1 g5687(.A (n_56), .Y (n_55));
  NAND2X2 g5688__2250(.A (n_53), .B (n_54), .Y (n_217));
  NAND2X2 g5689__6083(.A (n_303), .B (n_52), .Y (n_56));
  NAND2BX1 g5690__2703(.AN (n_43), .B (n_44), .Y (n_54));
  NAND2X1 g5691__5795(.A (n_43), .B (n_45), .Y (n_53));
  NOR2X2 g5692__7344(.A (n_6), .B (n_43), .Y (n_52));
  NAND3X1 g5694__1840(.A (u2_m3[3]), .B (n_40), .C (n_41), .Y (n_50));
  OAI21X2 g5695__5019(.A0 (n_8), .A1 (n_6), .B0 (n_41), .Y (n_51));
  OAI21X1 g5696__1857(.A0 (u2_m3[3]), .A1 (n_40), .B0 (n_47), .Y
       (n_49));
  NAND2XL g5697__9906(.A (u2_m3[3]), .B (n_39), .Y (n_47));
  NAND2X2 g5698__8780(.A (n_41), .B (n_7), .Y (n_46));
  NOR2BX1 g5699__4296(.AN (n_40), .B (n_39), .Y (n_48));
  INVX1 g5700(.A (n_44), .Y (n_45));
  OR2X1 g5701__3772(.A (u2_m3[3]), .B (n_39), .Y (n_42));
  NAND2X1 g5702__1474(.A (n_8), .B (n_304), .Y (n_44));
  NAND2X2 g5703__4547(.A (n_34), .B (n_28), .Y (n_43));
  NAND2X2 g5704__9682(.A (n_33), .B (n_31), .Y (n_41));
  NAND2XL g5705__2683(.A (u2_m3[2]), .B (n_32), .Y (n_40));
  NOR2XL g5706__1309(.A (u2_m3[2]), .B (n_32), .Y (n_39));
  NAND2X1 g5712__6877(.A (n_18), .B (n_30), .Y (n_34));
  NAND2X2 g5714__2900(.A (n_25), .B (n_4), .Y (n_8));
  NOR2BX1 g5718__7675(.AN (n_30), .B (n_29), .Y (n_215));
  OAI21X2 g5719__7118(.A0 (n_15), .A1 (n_17), .B0 (n_16), .Y (n_33));
  OAI2BB1X1 g5720__8757(.A0N (u2_m3[1]), .A1N (u2_m2[3]), .B0 (n_27),
       .Y (n_32));
  OAI22X4 g5722__1786(.A0 (n_14), .A1 (n_23), .B0 (u2_m1[3]), .B1
       (n_26), .Y (n_31));
  NOR2BX1 g5723__5953(.AN (n_24), .B (u2_m0[2]), .Y (n_29));
  NAND2BX2 g5724__5703(.AN (n_24), .B (u2_m0[2]), .Y (n_30));
  OAI21XL g5725__7114(.A0 (u2_m2[3]), .A1 (u2_m3[1]), .B0 (u2_m1[3]),
       .Y (n_27));
  AOI21X2 g5726__5266(.A0 (n_329), .A1 (n_0), .B0 (n_1), .Y (n_28));
  CLKINVX4 g5727(.A (n_23), .Y (n_26));
  OAI21X1 g5729__2250(.A0 (n_13), .A1 (n_21), .B0 (n_20), .Y (n_25));
  OAI21X1 g5730__6083(.A0 (u2_m1[0]), .A1 (u2_m2[0]), .B0 (n_18), .Y
       (n_24));
  OAI22X4 g5731__2703(.A0 (u2_m2[3]), .A1 (n_319), .B0 (u2_m3[1]), .B1
       (n_310), .Y (n_23));
  NOR2X1 g5734__5795(.A (u2_m2[1]), .B (u2_m0[3]), .Y (n_21));
  NAND2XL g5735__7344(.A (u2_m2[1]), .B (u2_m0[3]), .Y (n_20));
  NAND2X1 g5736__1840(.A (u2_m2[1]), .B (n_13), .Y (n_22));
  NOR2X2 g5738__5019(.A (u2_m3[0]), .B (n_321), .Y (n_17));
  NOR2X1 g5739__1857(.A (u2_m2[1]), .B (n_13), .Y (n_19));
  NAND2X2 g5740__9906(.A (u2_m3[0]), .B (n_321), .Y (n_16));
  NAND2XL g5741__8780(.A (u2_m2[0]), .B (u2_m1[0]), .Y (n_18));
  INVX1 g5742(.A (u2_m1[2]), .Y (n_15));
  CLKINVX1 g5743(.A (u2_m1[3]), .Y (n_14));
  CLKINVX1 g5744(.A (u2_m1[1]), .Y (n_13));
  OR2X1 g5693__4296(.A (n_33), .B (n_31), .Y (n_7));
  NOR2X2 g5750__3772(.A (n_33), .B (n_31), .Y (n_6));
  XNOR3X1 g5751__1474(.A (u2_m3[0]), .B (u2_m2[2]), .C (u2_m1[2]), .Y
       (n_5));
  XOR3X1 g5752__4547(.A (u2_m3[0]), .B (u2_m2[2]), .C (u2_m1[2]), .Y
       (n_4));
  NAND3BX1 g5759__9682(.AN (n_51), .B (n_48), .C (n_56), .Y (n_2));
  XOR3X1 g5760__2683(.A (n_18), .B (n_30), .C (n_276), .Y (n_216));
  NOR3BX1 g5761__1309(.AN (n_22), .B (n_19), .C (n_329), .Y (n_1));
  NAND2BX1 g5762__6877(.AN (n_19), .B (n_22), .Y (n_0));
  MXI2XL csa_tree_add_69_22_groupi_g1247__2900(.A
       (csa_tree_add_69_22_groupi_n_100), .B
       (csa_tree_add_69_22_groupi_n_99), .S0 (n_226), .Y (p[15]));
  MXI2X1 csa_tree_add_69_22_groupi_g1248__2391(.A
       (csa_tree_add_69_22_groupi_n_107), .B
       (csa_tree_add_69_22_groupi_n_106), .S0
       (csa_tree_add_69_22_groupi_n_66), .Y (p[11]));
  MXI2XL csa_tree_add_69_22_groupi_g1249__7675(.A
       (csa_tree_add_69_22_groupi_n_105), .B
       (csa_tree_add_69_22_groupi_n_104), .S0 (n_225), .Y (p[14]));
  MXI2XL csa_tree_add_69_22_groupi_g1250__7118(.A
       (csa_tree_add_69_22_groupi_n_109), .B
       (csa_tree_add_69_22_groupi_n_108), .S0 (n_224), .Y (p[13]));
  INVXL csa_tree_add_69_22_groupi_g1251(.A
       (csa_tree_add_69_22_groupi_n_108), .Y
       (csa_tree_add_69_22_groupi_n_109));
  OAI21X1 csa_tree_add_69_22_groupi_g1252__8757(.A0
       (csa_tree_add_69_22_groupi_n_44), .A1
       (csa_tree_add_69_22_groupi_n_97), .B0 (n_333), .Y
       (csa_tree_add_69_22_groupi_n_108));
  INVX1 csa_tree_add_69_22_groupi_g1253(.A
       (csa_tree_add_69_22_groupi_n_106), .Y
       (csa_tree_add_69_22_groupi_n_107));
  OAI21X1 csa_tree_add_69_22_groupi_g1254__1786(.A0 (n_261), .A1
       (csa_tree_add_69_22_groupi_n_96), .B0
       (csa_tree_add_69_22_groupi_n_53), .Y
       (csa_tree_add_69_22_groupi_n_106));
  INVXL csa_tree_add_69_22_groupi_g1255(.A
       (csa_tree_add_69_22_groupi_n_104), .Y
       (csa_tree_add_69_22_groupi_n_105));
  OAI21X1 csa_tree_add_69_22_groupi_g1256__5953(.A0
       (csa_tree_add_69_22_groupi_n_67), .A1
       (csa_tree_add_69_22_groupi_n_97), .B0
       (csa_tree_add_69_22_groupi_n_61), .Y
       (csa_tree_add_69_22_groupi_n_104));
  MXI2X1 csa_tree_add_69_22_groupi_g1257__5703(.A
       (csa_tree_add_69_22_groupi_n_0), .B
       (csa_tree_add_69_22_groupi_n_1), .S0
       (csa_tree_add_69_22_groupi_n_68), .Y (p[12]));
  OAI21XL csa_tree_add_69_22_groupi_g1258__7114(.A0
       (csa_tree_add_69_22_groupi_n_96), .A1
       (csa_tree_add_69_22_groupi_n_65), .B0
       (csa_tree_add_69_22_groupi_n_98), .Y (p[10]));
  MXI2X1 csa_tree_add_69_22_groupi_g1259__5266(.A
       (csa_tree_add_69_22_groupi_n_95), .B
       (csa_tree_add_69_22_groupi_n_94), .S0
       (csa_tree_add_69_22_groupi_n_69), .Y (p[9]));
  INVXL csa_tree_add_69_22_groupi_g1260(.A
       (csa_tree_add_69_22_groupi_n_99), .Y
       (csa_tree_add_69_22_groupi_n_100));
  OAI21X1 csa_tree_add_69_22_groupi_g1261__2250(.A0
       (csa_tree_add_69_22_groupi_n_76), .A1
       (csa_tree_add_69_22_groupi_n_97), .B0
       (csa_tree_add_69_22_groupi_n_75), .Y
       (csa_tree_add_69_22_groupi_n_99));
  OAI211X1 csa_tree_add_69_22_groupi_g1262__6083(.A0 (n_279), .A1
       (n_314), .B0 (n_255), .C0 (csa_tree_add_69_22_groupi_n_65), .Y
       (csa_tree_add_69_22_groupi_n_98));
  NOR2X2 csa_tree_add_69_22_groupi_g1264__2703(.A
       (csa_tree_add_69_22_groupi_n_92), .B
       (csa_tree_add_69_22_groupi_n_80), .Y
       (csa_tree_add_69_22_groupi_n_97));
  AOI21X1 csa_tree_add_69_22_groupi_g1265__5795(.A0 (n_313), .A1
       (n_280), .B0 (n_256), .Y (csa_tree_add_69_22_groupi_n_96));
  INVX1 csa_tree_add_69_22_groupi_g1266(.A
       (csa_tree_add_69_22_groupi_n_94), .Y
       (csa_tree_add_69_22_groupi_n_95));
  OAI21X1 csa_tree_add_69_22_groupi_g1267__7344(.A0
       (csa_tree_add_69_22_groupi_n_51), .A1 (n_314), .B0
       (csa_tree_add_69_22_groupi_n_54), .Y
       (csa_tree_add_69_22_groupi_n_94));
  MXI2XL csa_tree_add_69_22_groupi_g1268__1840(.A (n_313), .B (n_312),
       .S0 (csa_tree_add_69_22_groupi_n_64), .Y (p[8]));
  NOR2X2 csa_tree_add_69_22_groupi_g1269__5019(.A
       (csa_tree_add_69_22_groupi_n_74), .B (n_312), .Y
       (csa_tree_add_69_22_groupi_n_92));
  AOI21X2 csa_tree_add_69_22_groupi_g1271__1857(.A0
       (csa_tree_add_69_22_groupi_n_83), .A1
       (csa_tree_add_69_22_groupi_n_85), .B0
       (csa_tree_add_69_22_groupi_n_84), .Y
       (csa_tree_add_69_22_groupi_n_90));
  MXI2X1 csa_tree_add_69_22_groupi_g1272__9906(.A
       (csa_tree_add_69_22_groupi_n_85), .B (n_259), .S0
       (csa_tree_add_69_22_groupi_n_86), .Y (p[7]));
  XOR3X1 csa_tree_add_69_22_groupi_g1274__8780(.A
       (csa_tree_add_69_22_groupi_n_82), .B (n_292), .C
       (csa_tree_add_69_22_groupi_n_60), .Y (p[6]));
  XNOR3X1 csa_tree_add_69_22_groupi_g1275__4296(.A
       (csa_tree_add_69_22_groupi_n_81), .B (n_275), .C (n_214), .Y
       (csa_tree_add_69_22_groupi_n_86));
  OAI21X2 csa_tree_add_69_22_groupi_g1276__3772(.A0
       (csa_tree_add_69_22_groupi_n_82), .A1
       (csa_tree_add_69_22_groupi_n_77), .B0
       (csa_tree_add_69_22_groupi_n_73), .Y
       (csa_tree_add_69_22_groupi_n_85));
  NOR2XL csa_tree_add_69_22_groupi_g1277__1474(.A
       (csa_tree_add_69_22_groupi_n_81), .B
       (csa_tree_add_69_22_groupi_n_22), .Y
       (csa_tree_add_69_22_groupi_n_84));
  NAND2X1 csa_tree_add_69_22_groupi_g1278__4547(.A
       (csa_tree_add_69_22_groupi_n_22), .B
       (csa_tree_add_69_22_groupi_n_81), .Y
       (csa_tree_add_69_22_groupi_n_83));
  ADDFXL csa_tree_add_69_22_groupi_g1279__9682(.A
       (csa_tree_add_69_22_groupi_n_38), .B (n_215), .CI (n_203), .CO
       (csa_tree_add_69_22_groupi_n_81), .S
       (csa_tree_add_69_22_groupi_n_82));
  NAND2X1 csa_tree_add_69_22_groupi_g1280__2683(.A
       (csa_tree_add_69_22_groupi_n_72), .B
       (csa_tree_add_69_22_groupi_n_79), .Y
       (csa_tree_add_69_22_groupi_n_80));
  NAND3X2 csa_tree_add_69_22_groupi_g1281__1309(.A
       (csa_tree_add_69_22_groupi_n_47), .B
       (csa_tree_add_69_22_groupi_n_46), .C
       (csa_tree_add_69_22_groupi_n_70), .Y
       (csa_tree_add_69_22_groupi_n_79));
  MXI2XL csa_tree_add_69_22_groupi_g1282__6877(.A
       (csa_tree_add_69_22_groupi_n_57), .B
       (csa_tree_add_69_22_groupi_n_56), .S0
       (csa_tree_add_69_22_groupi_n_41), .Y (p[5]));
  CLKAND2X2 csa_tree_add_69_22_groupi_g1283__2900(.A (n_292), .B
       (csa_tree_add_69_22_groupi_n_58), .Y
       (csa_tree_add_69_22_groupi_n_77));
  NAND2BX1 csa_tree_add_69_22_groupi_g1284__2391(.AN
       (csa_tree_add_69_22_groupi_n_67), .B (n_225), .Y
       (csa_tree_add_69_22_groupi_n_76));
  NAND2BX1 csa_tree_add_69_22_groupi_g1285__7675(.AN
       (csa_tree_add_69_22_groupi_n_61), .B (n_225), .Y
       (csa_tree_add_69_22_groupi_n_75));
  NAND3X2 csa_tree_add_69_22_groupi_g1286__7118(.A
       (csa_tree_add_69_22_groupi_n_46), .B
       (csa_tree_add_69_22_groupi_n_47), .C
       (csa_tree_add_69_22_groupi_n_62), .Y
       (csa_tree_add_69_22_groupi_n_74));
  NAND2BX1 csa_tree_add_69_22_groupi_g1287__8757(.AN (n_292), .B
       (csa_tree_add_69_22_groupi_n_59), .Y
       (csa_tree_add_69_22_groupi_n_73));
  AOI21X1 csa_tree_add_69_22_groupi_g1288__1786(.A0
       (csa_tree_add_69_22_groupi_n_52), .A1
       (csa_tree_add_69_22_groupi_n_47), .B0
       (csa_tree_add_69_22_groupi_n_49), .Y
       (csa_tree_add_69_22_groupi_n_72));
  OAI21X2 csa_tree_add_69_22_groupi_g1290__5953(.A0
       (csa_tree_add_69_22_groupi_n_54), .A1
       (csa_tree_add_69_22_groupi_n_43), .B0
       (csa_tree_add_69_22_groupi_n_48), .Y
       (csa_tree_add_69_22_groupi_n_70));
  NOR2BXL csa_tree_add_69_22_groupi_g1291__5703(.AN
       (csa_tree_add_69_22_groupi_n_48), .B
       (csa_tree_add_69_22_groupi_n_43), .Y
       (csa_tree_add_69_22_groupi_n_69));
  NAND2BX1 csa_tree_add_69_22_groupi_g1292__7114(.AN
       (csa_tree_add_69_22_groupi_n_44), .B (n_333), .Y
       (csa_tree_add_69_22_groupi_n_68));
  NAND2BX1 csa_tree_add_69_22_groupi_g1293__5266(.AN
       (csa_tree_add_69_22_groupi_n_44), .B (n_224), .Y
       (csa_tree_add_69_22_groupi_n_67));
  NOR2BXL csa_tree_add_69_22_groupi_g1294__2250(.AN
       (csa_tree_add_69_22_groupi_n_47), .B
       (csa_tree_add_69_22_groupi_n_49), .Y
       (csa_tree_add_69_22_groupi_n_66));
  CLKAND2X2 csa_tree_add_69_22_groupi_g1295__6083(.A (n_262), .B
       (csa_tree_add_69_22_groupi_n_53), .Y
       (csa_tree_add_69_22_groupi_n_65));
  NAND2XL csa_tree_add_69_22_groupi_g1296__2703(.A
       (csa_tree_add_69_22_groupi_n_3), .B
       (csa_tree_add_69_22_groupi_n_54), .Y
       (csa_tree_add_69_22_groupi_n_64));
  CLKAND2X2 csa_tree_add_69_22_groupi_g1298__5795(.A
       (csa_tree_add_69_22_groupi_n_42), .B
       (csa_tree_add_69_22_groupi_n_3), .Y
       (csa_tree_add_69_22_groupi_n_62));
  NAND2BX1 csa_tree_add_69_22_groupi_g1299__7344(.AN
       (csa_tree_add_69_22_groupi_n_55), .B (n_224), .Y
       (csa_tree_add_69_22_groupi_n_61));
  INVXL csa_tree_add_69_22_groupi_g1300(.A
       (csa_tree_add_69_22_groupi_n_59), .Y
       (csa_tree_add_69_22_groupi_n_60));
  INVX1 csa_tree_add_69_22_groupi_g1301(.A
       (csa_tree_add_69_22_groupi_n_58), .Y
       (csa_tree_add_69_22_groupi_n_59));
  AOI21X1 csa_tree_add_69_22_groupi_g1302__1840(.A0
       (csa_tree_add_69_22_groupi_n_2), .A1
       (csa_tree_add_69_22_groupi_n_8), .B0
       (csa_tree_add_69_22_groupi_n_50), .Y
       (csa_tree_add_69_22_groupi_n_58));
  INVXL csa_tree_add_69_22_groupi_g1303(.A
       (csa_tree_add_69_22_groupi_n_56), .Y
       (csa_tree_add_69_22_groupi_n_57));
  MXI2X1 csa_tree_add_69_22_groupi_g1304__5019(.A
       (csa_tree_add_69_22_groupi_n_9), .B
       (csa_tree_add_69_22_groupi_n_8), .S0
       (csa_tree_add_69_22_groupi_n_39), .Y
       (csa_tree_add_69_22_groupi_n_56));
  INVX1 csa_tree_add_69_22_groupi_g1305(.A
       (csa_tree_add_69_22_groupi_n_52), .Y
       (csa_tree_add_69_22_groupi_n_53));
  INVXL csa_tree_add_69_22_groupi_g1306(.A
       (csa_tree_add_69_22_groupi_n_3), .Y
       (csa_tree_add_69_22_groupi_n_51));
  AOI31X1 csa_tree_add_69_22_groupi_g1308__1857(.A0 (n_212), .A1
       (csa_tree_add_69_22_groupi_n_21), .A2 (n_211), .B0
       (csa_tree_add_69_22_groupi_n_39), .Y
       (csa_tree_add_69_22_groupi_n_50));
  NAND2X1 csa_tree_add_69_22_groupi_g1309__9906(.A (n_223), .B
       (csa_tree_add_69_22_groupi_n_34), .Y
       (csa_tree_add_69_22_groupi_n_55));
  NAND2X2 csa_tree_add_69_22_groupi_g1310__8780(.A
       (csa_tree_add_69_22_groupi_n_36), .B (n_327), .Y
       (csa_tree_add_69_22_groupi_n_54));
  NOR2BX1 csa_tree_add_69_22_groupi_g1311__4296(.AN
       (csa_tree_add_69_22_groupi_n_33), .B (n_294), .Y
       (csa_tree_add_69_22_groupi_n_52));
  NAND2BX1 csa_tree_add_69_22_groupi_g1312__3772(.AN
       (csa_tree_add_69_22_groupi_n_27), .B
       (csa_tree_add_69_22_groupi_n_20), .Y
       (csa_tree_add_69_22_groupi_n_3));
  CLKINVX1 csa_tree_add_69_22_groupi_g1314(.A
       (csa_tree_add_69_22_groupi_n_42), .Y
       (csa_tree_add_69_22_groupi_n_43));
  NOR2XL csa_tree_add_69_22_groupi_g1315__1474(.A
       (csa_tree_add_69_22_groupi_n_29), .B
       (csa_tree_add_69_22_groupi_n_40), .Y
       (csa_tree_add_69_22_groupi_n_49));
  NAND2X2 csa_tree_add_69_22_groupi_g1316__4547(.A
       (csa_tree_add_69_22_groupi_n_31), .B
       (csa_tree_add_69_22_groupi_n_37), .Y
       (csa_tree_add_69_22_groupi_n_48));
  NAND2BX2 csa_tree_add_69_22_groupi_g1317__9682(.AN
       (csa_tree_add_69_22_groupi_n_32), .B
       (csa_tree_add_69_22_groupi_n_29), .Y
       (csa_tree_add_69_22_groupi_n_47));
  NAND2BX2 csa_tree_add_69_22_groupi_g1318__2683(.AN
       (csa_tree_add_69_22_groupi_n_33), .B (n_294), .Y
       (csa_tree_add_69_22_groupi_n_46));
  NOR2X1 csa_tree_add_69_22_groupi_g1319__1309(.A (n_223), .B
       (csa_tree_add_69_22_groupi_n_34), .Y
       (csa_tree_add_69_22_groupi_n_44));
  NAND2BX1 csa_tree_add_69_22_groupi_g1320__6877(.AN
       (csa_tree_add_69_22_groupi_n_31), .B
       (csa_tree_add_69_22_groupi_n_30), .Y
       (csa_tree_add_69_22_groupi_n_42));
  BUFX2 csa_tree_add_69_22_groupi_g1321(.A
       (csa_tree_add_69_22_groupi_n_2), .Y
       (csa_tree_add_69_22_groupi_n_41));
  INVXL csa_tree_add_69_22_groupi_g1322(.A
       (csa_tree_add_69_22_groupi_n_32), .Y
       (csa_tree_add_69_22_groupi_n_40));
  ADDFX1 csa_tree_add_69_22_groupi_g1323__2900(.A (u2_m0[1]), .B
       (csa_tree_add_69_22_groupi_n_14), .CI (u1_m0[1]), .CO
       (csa_tree_add_69_22_groupi_n_38), .S
       (csa_tree_add_69_22_groupi_n_39));
  INVXL csa_tree_add_69_22_groupi_g1324(.A
       (csa_tree_add_69_22_groupi_n_30), .Y
       (csa_tree_add_69_22_groupi_n_37));
  CLKINVX1 csa_tree_add_69_22_groupi_g1325(.A
       (csa_tree_add_69_22_groupi_n_20), .Y
       (csa_tree_add_69_22_groupi_n_36));
  AOI21X1 csa_tree_add_69_22_groupi_g1326__2391(.A0
       (csa_tree_add_69_22_groupi_n_19), .A1
       (csa_tree_add_69_22_groupi_n_7), .B0
       (csa_tree_add_69_22_groupi_n_26), .Y (p[4]));
  OAI2BB1X1 csa_tree_add_69_22_groupi_g1327__7675(.A0N (n_346), .A1N
       (n_337), .B0 (csa_tree_add_69_22_groupi_n_23), .Y
       (csa_tree_add_69_22_groupi_n_34));
  OAI2BB1X1 csa_tree_add_69_22_groupi_g1328__7118(.A0N (u3_m0[1]), .A1N
       (csa_tree_add_69_22_groupi_n_5), .B0
       (csa_tree_add_69_22_groupi_n_24), .Y
       (csa_tree_add_69_22_groupi_n_33));
  OAI21X1 csa_tree_add_69_22_groupi_g1329__8757(.A0
       (csa_tree_add_69_22_groupi_n_6), .A1
       (csa_tree_add_69_22_groupi_n_16), .B0
       (csa_tree_add_69_22_groupi_n_12), .Y
       (csa_tree_add_69_22_groupi_n_32));
  OAI2BB1X1 csa_tree_add_69_22_groupi_g1330__1786(.A0N (u3_m0[0]), .A1N
       (n_217), .B0 (csa_tree_add_69_22_groupi_n_25), .Y
       (csa_tree_add_69_22_groupi_n_31));
  XNOR3X1 csa_tree_add_69_22_groupi_g1331__5953(.A (u3_m0[1]), .B
       (n_218), .C (n_206), .Y (csa_tree_add_69_22_groupi_n_30));
  XNOR3X1 csa_tree_add_69_22_groupi_g1332__5703(.A (n_346), .B (n_220),
       .C (n_208), .Y (csa_tree_add_69_22_groupi_n_29));
  XOR3X1 csa_tree_add_69_22_groupi_g1334__5266(.A (u3_m0[0]), .B
       (n_217), .C (n_205), .Y (csa_tree_add_69_22_groupi_n_27));
  INVXL csa_tree_add_69_22_groupi_g1335(.A
       (csa_tree_add_69_22_groupi_n_2), .Y
       (csa_tree_add_69_22_groupi_n_26));
  NAND2X1 csa_tree_add_69_22_groupi_g1337__2250(.A
       (csa_tree_add_69_22_groupi_n_21), .B (n_211), .Y
       (csa_tree_add_69_22_groupi_n_2));
  OAI21X1 csa_tree_add_69_22_groupi_g1338__6083(.A0 (u3_m0[0]), .A1
       (n_217), .B0 (n_205), .Y (csa_tree_add_69_22_groupi_n_25));
  OAI21X1 csa_tree_add_69_22_groupi_g1339__2703(.A0 (u3_m0[1]), .A1
       (csa_tree_add_69_22_groupi_n_5), .B0 (n_206), .Y
       (csa_tree_add_69_22_groupi_n_24));
  OAI21XL csa_tree_add_69_22_groupi_g1340__5795(.A0 (n_337), .A1
       (n_346), .B0 (n_208), .Y (csa_tree_add_69_22_groupi_n_23));
  MXI2X1 csa_tree_add_69_22_groupi_g1341__7344(.A (n_214), .B
       (csa_tree_add_69_22_groupi_n_10), .S0 (n_275), .Y
       (csa_tree_add_69_22_groupi_n_22));
  INVX1 csa_tree_add_69_22_groupi_g1342(.A
       (csa_tree_add_69_22_groupi_n_19), .Y
       (csa_tree_add_69_22_groupi_n_21));
  ACHCONX2 csa_tree_add_69_22_groupi_g1343__1840(.A (n_204), .B
       (csa_tree_add_69_22_groupi_n_11), .CI (n_214), .CON
       (csa_tree_add_69_22_groupi_n_20));
  OAI21X1 csa_tree_add_69_22_groupi_g1344__5019(.A0 (u1_m0[0]), .A1
       (u2_m0[0]), .B0 (csa_tree_add_69_22_groupi_n_13), .Y
       (csa_tree_add_69_22_groupi_n_19));
  NOR2XL csa_tree_add_69_22_groupi_g1347__8780(.A (n_296), .B (n_219),
       .Y (csa_tree_add_69_22_groupi_n_16));
  INVX1 csa_tree_add_69_22_groupi_g1349(.A
       (csa_tree_add_69_22_groupi_n_13), .Y
       (csa_tree_add_69_22_groupi_n_14));
  NAND2XL csa_tree_add_69_22_groupi_g1350__3772(.A (u2_m0[0]), .B
       (u1_m0[0]), .Y (csa_tree_add_69_22_groupi_n_13));
  NAND2XL csa_tree_add_69_22_groupi_g1351__1474(.A (n_296), .B (n_219),
       .Y (csa_tree_add_69_22_groupi_n_12));
  BUFX2 csa_tree_add_69_22_groupi_g1352(.A (n_216), .Y
       (csa_tree_add_69_22_groupi_n_11));
  INVXL csa_tree_add_69_22_groupi_g1353(.A (n_214), .Y
       (csa_tree_add_69_22_groupi_n_10));
  INVX1 csa_tree_add_69_22_groupi_g1354(.A
       (csa_tree_add_69_22_groupi_n_8), .Y
       (csa_tree_add_69_22_groupi_n_9));
  CLKINVX1 csa_tree_add_69_22_groupi_g1355(.A (n_212), .Y
       (csa_tree_add_69_22_groupi_n_8));
  INVXL csa_tree_add_69_22_groupi_g1356(.A (n_211), .Y
       (csa_tree_add_69_22_groupi_n_7));
  INVX1 csa_tree_add_69_22_groupi_g1357(.A (n_207), .Y
       (csa_tree_add_69_22_groupi_n_6));
  CLKBUFX2 csa_tree_add_69_22_groupi_g1358(.A (n_218), .Y
       (csa_tree_add_69_22_groupi_n_5));
  INVXL csa_tree_add_69_22_groupi_fopt(.A
       (csa_tree_add_69_22_groupi_n_0), .Y
       (csa_tree_add_69_22_groupi_n_1));
  INVXL csa_tree_add_69_22_groupi_fopt1359(.A
       (csa_tree_add_69_22_groupi_n_97), .Y
       (csa_tree_add_69_22_groupi_n_0));
  INVXL fopt(.A (n_256), .Y (n_255));
  CLKBUFX2 fopt5763(.A (csa_tree_add_69_22_groupi_n_70), .Y (n_256));
  CLKINVX1 fopt5765(.A (csa_tree_add_69_22_groupi_n_85), .Y (n_259));
  INVXL fopt5766(.A (n_262), .Y (n_261));
  CLKBUFX2 fopt5767(.A (csa_tree_add_69_22_groupi_n_46), .Y (n_262));
  MXI2X1 g2(.A (n_66), .B (u1_m1[3]), .S0 (n_77), .Y (n_268));
  XNOR2X1 g5774(.A (n_216), .B (n_204), .Y (n_275));
  BUFX3 fopt5775(.A (n_28), .Y (n_276));
  INVXL fopt5776(.A (n_280), .Y (n_279));
  CLKBUFX2 fopt5777(.A (csa_tree_add_69_22_groupi_n_62), .Y (n_280));
  INVX2 fopt5779(.A (u1_m2[3]), .Y (n_283));
  CLKINVX1 fopt5781(.A (u1_m1[1]), .Y (n_286));
  XNOR2X1 g5784(.A (n_291), .B (n_174), .Y (n_292));
  NAND2BXL g3(.AN (n_152), .B (n_149), .Y (n_291));
  XOR3X1 g5785(.A (n_293), .B (n_219), .C (n_207), .Y (n_294));
  XNOR3XL g5786(.A (u3_m0[2]), .B (u3_m1[0]), .C (u3_m2[0]), .Y
       (n_293));
  CLKXOR2X1 g3985__5787(.A (u3_m0[2]), .B (n_295), .Y (n_296));
  CLKXOR2X1 g3986__5788(.A (u3_m1[0]), .B (u3_m2[0]), .Y (n_295));
  NAND2X2 g5789(.A (n_297), .B (n_143), .Y (n_298));
  XOR3X1 g5790(.A (u0_m3[0]), .B (u0_m1[2]), .C (u0_m2[2]), .Y (n_297));
  NAND2BX1 g5793(.AN (n_194), .B (n_191), .Y (n_301));
  NAND2BXL g5795(.AN (n_25), .B (n_5), .Y (n_303));
  INVX1 g5796(.A (n_304), .Y (n_305));
  NAND2BX1 g5715__5797(.AN (n_25), .B (n_5), .Y (n_304));
  OAI2BB1X1 g5798(.A0N (u0_m2[0]), .A1N (u0_m1[0]), .B0 (n_115), .Y
       (n_306));
  NAND2X1 g5000__5799(.A (u0_m2[0]), .B (u0_m1[0]), .Y (n_307));
  NAND2BX2 g5800(.AN (n_135), .B (n_308), .Y (n_309));
  XNOR3X1 g5801(.A (u0_m3[0]), .B (u0_m1[2]), .C (u0_m2[2]), .Y
       (n_308));
  INVX4 fopt5802(.A (u2_m2[3]), .Y (n_310));
  CLKINVX1 fopt5805(.A (n_313), .Y (n_314));
  INVX2 fopt5806(.A (n_312), .Y (n_313));
  CLKINVX2 fopt5807(.A (csa_tree_add_69_22_groupi_n_90), .Y (n_312));
  INVXL fopt5808(.A (n_8), .Y (n_317));
  CLKINVX3 fopt5809(.A (u2_m3[1]), .Y (n_319));
  INVX2 fopt5811(.A (n_323), .Y (n_321));
  CLKINVX1 fopt5812(.A (u2_m2[2]), .Y (n_323));
  BUFX2 fopt5814(.A (csa_tree_add_69_22_groupi_n_27), .Y (n_327));
  INVX1 fopt5816(.A (n_331), .Y (n_329));
  INVX1 fopt5817(.A (u2_m0[3]), .Y (n_331));
  INVXL fopt5818(.A (n_335), .Y (n_333));
  CLKINVX1 fopt5820(.A (csa_tree_add_69_22_groupi_n_55), .Y (n_335));
  CLKBUFX2 fopt5821(.A (n_220), .Y (n_337));
  NAND3BX1 g5823(.AN (n_116), .B (n_168), .C (n_117), .Y (n_342));
  XNOR2X1 g5827(.A (n_194), .B (n_191), .Y (n_346));
  AND2X1 g5828(.A (n_82), .B (n_268), .Y (n_347));
  OA21XL g5829(.A0 (n_147), .A1 (n_298), .B0 (n_151), .Y (n_348));
endmodule

module project(clk, a, b, p);
  input clk;
  input [7:0] a, b;
  output [15:0] p;
  wire clk;
  wire [7:0] a, b;
  wire [15:0] p;
  wire [15:0] product;
  vedic_8x8_comb vm(.a (a), .b (b), .p (product));
  DFFHQX1 \p_reg[14] (.CK (clk), .D (product[14]), .Q (p[14]));
  DFFHQX1 \p_reg[12] (.CK (clk), .D (product[12]), .Q (p[12]));
  DFFHQX1 \p_reg[8] (.CK (clk), .D (product[8]), .Q (p[8]));
  DFFHQX1 \p_reg[15] (.CK (clk), .D (product[15]), .Q (p[15]));
  DFFHQX1 \p_reg[7] (.CK (clk), .D (product[7]), .Q (p[7]));
  DFFHQX1 \p_reg[11] (.CK (clk), .D (product[11]), .Q (p[11]));
  DFFHQX1 \p_reg[6] (.CK (clk), .D (product[6]), .Q (p[6]));
  DFFHQX1 \p_reg[13] (.CK (clk), .D (product[13]), .Q (p[13]));
  DFFHQX1 \p_reg[10] (.CK (clk), .D (product[10]), .Q (p[10]));
  DFFQXL \p_reg[4] (.CK (clk), .D (product[4]), .Q (p[4]));
  DFFHQX1 \p_reg[5] (.CK (clk), .D (product[5]), .Q (p[5]));
  DFFHQX1 \p_reg[9] (.CK (clk), .D (product[9]), .Q (p[9]));
  DFFQXL \p_reg[2] (.CK (clk), .D (product[2]), .Q (p[2]));
  DFFQXL \p_reg[3] (.CK (clk), .D (product[3]), .Q (p[3]));
  DFFQXL \p_reg[1] (.CK (clk), .D (product[1]), .Q (p[1]));
  DFFQXL \p_reg[0] (.CK (clk), .D (product[0]), .Q (p[0]));
endmodule

